proxy-providers:
  Online:
    type: http
    url: "https://raw.githubusercontent.com/snja/clash-config/refs/heads/main/proxy_provider/trojan.yaml"
    path: "./proxy_provider/online.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
    interval: 400
    
  Local:
    type: file
    path: "./proxy_provider/trojan.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 30



proxy-groups:
- name: Ping
  type: url-test
  disable-udp: false
  use:
  - Local
  - Online

- name: Backup
  type: fallback
  disable-udp: false
  use:
  - Local
  - Online

- name: Semua
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - Local
  - Online

- name: Github
  type: fallback
  disable-udp: false
  use:
  - Local
  proxies:
  - DIRECT


rule-providers:
  Direct:
    type: file
    behavior: classical
    path: "./rule_provider/direct.yaml"
  Reject:
    type: file
    behavior: classical
    path: "./rule_provider/reject.yaml"







redir-port: 7892
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
unified-delay: true
external-controller: 0.0.0.0:9090
secret: reyre
bind-address: 0.0.0.0
external-ui: ui
tproxy-port: 7895
tcp-concurrent: true	
enable-process: true
find-process-mode: always
ipv6: true

experimental:
  ignore-resolve-fail: true
  sniff-tls-sni: true
  tracing: true
hosts:
  "localhost": 127.0.0.1
profile:
  store-selected: true
  store-fake-ip: true

tun:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:53
  stack: gvisor
  dns-hijack:
     - "any:53"
     - "tcp://any:53"
  auto-redir: true
  auto-route: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: true
  default-nameserver:
    - '8.8.8.8'
    - '1.1.1.1'

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - '*.lan'
    - '+.msftncsi.com'
    - msftconnecttest.com
    - 'time?.*.com'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.apple.com'
    - time-ios.apple.com
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp?.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '+.pool.ntp.org'
    - '+.ipv6.microsoft.com'
    - speedtest.cros.wr.pvp.net
    - network-test.debian.org
    - detectportal.firefox.com
    - cable.auth.com
    - miwifi.com
    - routerlogin.com
    - routerlogin.net
    - tendawifi.com
    - tendawifi.net
    - tplinklogin.net
    - tplinkwifi.net
    - '*.xiami.com'
    - tplinkrepeater.net
    - router.asus.com
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - '*.openwrt.pool.ntp.org'
    - resolver1.opendns.com
    - 'GC._msDCS.*.*'
    - 'DC._msDCS.*.*'
    - 'PDC._msDCS.*.*'
  use-hosts: true
  nameserver:
    - "https://dns.quad9.net/dns-query"

rules:
  - DOMAIN-SUFFIX,raw.githubusercontent.com,Github
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,169.254.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,224.0.0.0/3,DIRECT
  - IP-CIDR6,::1/128,DIRECT
  - IP-CIDR6,fc00::/7,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - IP-CIDR6,fd00::/8,DIRECT
  - RULE-SET,Direct,DIRECT
  - RULE-SET,Reject,REJECT
  - MATCH,GLOBAL
