proxy-providers:
  Online:
    type: http
    url: https://raw.githubusercontent.com/snja/clash-config/refs/heads/main/proxy_provider/trojan.yaml
    path: "./proxy_provider/online.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
    interval: 400

proxy-groups:
- name: Utama
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - Online
  interface-name: eth1

- name: Backup
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  interface-name: eth2

- name: Auto
  type: fallback
  disable-udp: false
  proxies:
  - Utama
  - Backup
  
- name: Github
  type: fallback
  disable-udp: false
  proxies:
  - Auto
  - DIRECT

rule-providers:
  Reject:
    type: file
    behavior: classical
    path: "./rule_provider/reject.yaml"
rules:
  - DOMAIN-SUFFIX,raw.githubusercontent.com,Github
#  - RULE-SET,Reject,REJECT
  - MATCH,Auto
